version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_ml_app
    ports:
      - "8000:8000"
    networks:
      - ml_network
    depends_on:
      - redis_db

  redis_db:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge